name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# allow pushing to GHCR with GITHUB_TOKEN
permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/manalac-luis/kubernetes-cicd-tutorial

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          provenance: false   # safe on GH runners, avoids some flaky networks

      - name: Update GitOps repo (only on push to main)
        if: github.event_name == 'push'
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}   # PAT with repo: write on rslim087a/grade-api-gitops
        run: |
          set -euo pipefail
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials

          rm -rf gitops
          git clone https://github.com/rslim087a/grade-api-gitops.git gitops
          cd gitops

          sed -i "s|image: ghcr.io/.*/.*:.*|image: ${{ env.IMAGE }}:${{ github.sha }}|g" deployment.yaml

          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes"
          git push -f https://${GIT_TOKEN}@github.com/rslim087a/grade-api-gitops.git main

